// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaWXdXBI4bK3UVqcc-WzqRrMahpztLCQU',
    appId: '1:1017222099502:web:cfc00c3e00e3651b0665bf',
    messagingSenderId: '1017222099502',
    projectId: 'paseowof',
    authDomain: 'paseowof.firebaseapp.com',
    storageBucket: 'paseowof.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxC7-K-3ExC8fv7WVu4jbDAzt0Y77buTM',
    appId: '1:1017222099502:android:ff1f7517ec2901760665bf',
    messagingSenderId: '1017222099502',
    projectId: 'paseowof',
    storageBucket: 'paseowof.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWWt7884vphD2GaCjO3P7anZ8njEIbkLc',
    appId: '1:1017222099502:ios:ef15f54a5c4c38af0665bf',
    messagingSenderId: '1017222099502',
    projectId: 'paseowof',
    storageBucket: 'paseowof.firebasestorage.app',
    iosBundleId: 'com.example.paseowof',
  );
}
